In [1]:
#Session Task - (3-7-24)

#Use iris flower dataset from sklearn library and use Naive bayes models to measure the performance of each.
#1. Accuracy_score
#2. Classification_report
#3. Confusion_matrix



import pandas as pd
import numpy as np

In [2]:
# Iris Dataset

In [6]:
df = pd.read_csv('iris.csv')

In [7]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
label_encoder = LabelEncoder()


In [10]:
label_encoder

LabelEncoder()

In [13]:
df['species'] = label_encoder.fit_transform(df['species'])

In [12]:
df

sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [14]:
X= df.drop(['species'], axis = 1)

In [15]:
X

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [16]:
y= df['species']

In [17]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int64

In [18]:
from sklearn.model_selection import train_test_split

In [21]:
X_train,X_test , y_train ,y_test = train_test_split(X,y, test_size=0.3, random_state = 45 )

In [22]:
X_train

sepal_length  sepal_width  petal_length  petal_width
21            5.1          3.7           1.5          0.4
111           6.4          2.7           5.3          1.9
62            6.0          2.2           4.0          1.0
117           7.7          3.8           6.7          2.2
37            4.9          3.1           1.5          0.1
..            ...          ...           ...          ...
68            6.2          2.2           4.5          1.5
95            5.7          3.0           4.2          1.2
32            5.2          4.1           1.5          0.1
124           6.7          3.3           5.7          2.1
131           7.9          3.8           6.4          2.0

[105 rows x 4 columns]

In [23]:
y_test

0      0
43     0
129    2
3      0
34     0
44     0
38     0
105    2
123    2
140    2
28     0
125    2
113    2
103    2
133    2
35     0
145    2
142    2
40     0
87     1
84     1
85     1
115    2
51     1
4      0
112    2
92     1
64     1
10     0
91     1
76     1
96     1
119    2
101    2
25     0
137    2
13     0
26     0
74     1
30     0
33     0
82     1
1      0
52     1
93     1
Name: species, dtype: int64

In [24]:
from sklearn.naive_bayes import GaussianNB

In [25]:
gnb = GaussianNB()


In [26]:
gnb.fit(X_train , y_train)

GaussianNB()

In [27]:
y_pred = gnb.predict(X_test)

In [28]:
y_pred

array([0, 0, 2, 0, 0, 0, 0, 2, 2, 2, 0, 2, 2, 2, 1, 0, 2, 2, 0, 1, 1, 1,
       2, 1, 0, 2, 1, 1, 0, 1, 1, 1, 1, 2, 0, 2, 0, 0, 1, 0, 0, 1, 0, 1,
       1])

In [29]:
gnb.score (X_test ,y_test)

0.9555555555555556

In [31]:
pr = gnb.predict([[4.9,3.1,1.5,0.1]])
pr
label_encoder.inverse_transform(pr)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


array([0])

In [32]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [33]:
acc= accuracy_score(y_test , y_test)
acc

1.0

In [34]:
cl = classification_report(y_test , y_test)

In [35]:
cl

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        17\n           1       1.00      1.00      1.00        13\n           2       1.00      1.00      1.00        15\n\n    accuracy                           1.00        45\n   macro avg       1.00      1.00      1.00        45\nweighted avg       1.00      1.00      1.00        45\n'

In [36]:
cm=confusion_matrix(y_test,y_pred)

In [37]:
cm

array([[17,  0,  0],
       [ 0, 13,  0],
       [ 0,  2, 13]])